sudo: false
language: python

python:
  - '2.7'

install:
  - pip install tox

env:
  - TOX_ENV=py27-test
  - TOX_ENV=py33-test
  - TOX_ENV=py34-test

script:
  - tox -e $TOX_ENV

deploy:
  provider: pypi
  user: auser
  password:
    secure: foo
  on:
    tags: true
    repo: timbu/nameko-management
